## Sprint2_Ex2_imágenes_numpy


### Nivel 1

Ejercicio 1
1. Crea un np.array de una dimensión, que incluya al menos 8 números enteros, data type int64. 
2. Muestra la dimensión y la forma de la matriz. .

In [ ]:
import numpy as np

In [10]:

array = np.array([1, 2, 3, 10, 40,19,99,32], dtype='int64')

print(array)
print("El array tiene el siguyente número de dimensiones: ",array.ndim)
print(array.shape)
print(array.dtype)

[ 1  2  3 10 40 19 99 32]
El array tiene el siguyente número de dimensiones:  1
(8,)
int64


#### - Exercici 2
De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts.



In [10]:
sum = 0

for i in range(len(array)):
    sum = sum + array[i]

print(sum)

206


In [18]:
print ("La media es: ",sum /len(array))

La media es:  25.75


[[1 2 3]
 [4 5 6]]


#### Ex 3.

1. Crea una matriu bidimensional amb una forma de 5 x 5. 
2. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [22]:
import numpy as np
#random Integer values
array_2= np.random.randint(1,20, size=(5,5))
#array_2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(array_2)
print("La dimension del array es: ",array_2.ndim)
print("La forma del array es: ",array_2.shape)
print(array_2.dtype)

[[10 12  4  1 18]
 [ 2  9  7  2  3]
 [11  4  6  6  9]
 [ 5  6 17 10 18]
 [12  4 14 18 10]]
La dimension del array es:  2
La forma del array es:  (5, 5)
int64


In [35]:
#[r,c]
#max in column axis=0
#max in row axis=1
maxElement = np.amax(array_2)
maxInColumn = np.amax(array_2, axis=0)
maxInRow = np.amax(array_2, axis=1)
print("El numero máximo de la matriz es: ",maxElement)
print("El numero maximo de cada colimna es: ",maxInColumn)
print("El numero maximo de cada fila es: ", maxInRow)

El numero máximo de la matriz es:  18
El numero maximo de cada colimna es:  [12 12 17 18 18]
El numero maximo de cada fila es:  [18  9 11 18 18]
